# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

foresight: myopic

countries: [BN, KH, ID, LA, MY, MM, PH, SG, TH, VN] 

enable:
  retrieve_databundle: false 
  retrieve_databundle_sector: false
  retrieve_cost_data: true 
  download_osm_data: false 
  build_natura_raster: false 
  build_cutout: false
  renewable_profiles: true 

scenario:
  ll: ["copt"] 
  clusters: [75]
  planning_horizons: 
  - 2030
  - 2035
  - 2040
  - 2045  
  - 2050  
  demand: 
  - "ASEAN"
  opts: [Co2L-3h] #Co2L-EQ0.8c- CO2 limit, 1H, 80% self sufficiency
  sopts:
  - "3h"

snapshots:
  start: "2018-01-01"
  end: "2019-01-01"

cluster_options:
  simplify_network:
    remove_stubs: false
    remove_stubs_across_borders: false
    p_threshold_drop_isolated: 0 
    p_threshold_merge_isolated: 0 
    s_threshold_fetch_isolated: 0.1 

subregion: 
  define_by_gadm:
    ID_Java-Bali: [ID.2_1, ID.4_1, ID.7_1, ID.9_1, ID.10_1, ID.11_1, ID.33_1]
    ID_Kalimantan: [ID.12_1, ID.13_1, ID.14_1, ID.34_1, ID.35_1]
    ID_Maluku: [ID.18_1, ID.19_1]
    ID_Nusa-Tenggara: [ID.20_1, ID.21_1]
    ID_Papua: [ID.22_1, ID.23_1]
    ID_Sulawesi: [ID.6_1, ID.25_1, ID.26_1, ID.27_1, ID.28_1, ID.29_1]
    ID_Sumatra: [ID.1_1, ID.3_1, ID.5_1, ID.8_1, ID.16_1, ID.17_1, ID.24_1, ID.30_1, ID.31_1, ID.32_1,]
    MY_Peninsular: [MY.1_1, MY.2_1, MY.3_1, MY.4_1, MY.6_1, MY.7_1, MY.8_1, MY.9_1, MY.10_1, MY.11_1, MY.12_1, MY.15_1, MY.16_1]
    MY_Sabah: [MY.5_1, MY.13_1]
    MY_Sarawak: [MY.14_1]
    PH_Luzon: [
      PH.1_1, PH.5_1, PH.7_1, PH.8_1, PH.10_1, PH.11_1, PH.12_1, PH.13_1, PH.17_1, PH.18_1, PH.19_1, PH.20_1, PH.23_1, 
      PH.24_1, PH.33_1, PH.34_1, PH.35_1, PH.37_1, H.38_1, PH.39_1, PH.40_1, PH.45_1, PH.46_1, PH.47_1, PH.50_1, PH.55_1, 
      PH.56_1, PH.57_1, PH.58_1, PH.59_1, PH.60_1, PH.61_1, PH.62_1, PH.63_1, PH.64_1, PH.65_1, PH.69_1, PH.76_1, PH.78_1]
    PH_Visayas: [
      PH.4_1, PH.6_1, PH.14_1, PH.15_1, PH.22_1, PH.25_1, PH.31_1, PH.32_1, PH.36_1, PH.43_1, PH.51_1, PH.52_1, PH.54_1, PH.66_1, PH.68_1, PH.71_1]
    PH_Mindanao: [
      PH.2_1, PH.3_1, PH.9_1, PH.16_1, PH.21_1, PH.26_1, PH.27_1, PH.28_1, PH.29_1, PH.30_1, PH.41_1, PH.42_1, PH.44_1, 
      PH.48_1, PH.49_1, PH.53_1, PH.67_1, PH.70_1, PH.72_1, PH.73_1, PH.74_1, PH.75_1, PH.77_1, PH.79_1, PH.80_1, PH.81_1]


load_options: 
  prediction_year: 2050  
  scale:
    electricity:
      2030:
        BN: 0.943
        ID: 1.116
        KH: 1.538
        LA: 0.56
        MM: 0.652
        MY: 0.956
        PH: 1.014
        SG: 0.81
        TH: 0.805
        VN: 1.413
      2035:
        BN: 0.819
        ID: 1.129
        KH: 1.568
        LA: 0.58
        MM: 0.692
        MY: 0.965
        PH: 1.027
        SG: 0.784
        TH: 0.82
        VN: 1.462
      2040:
        BN: 0.711
        ID: 1.136
        KH: 1.587
        LA: 0.586
        MM: 0.73
        MY: 0.969
        PH: 1.032
        SG: 0.746
        TH: 0.83
        VN: 1.503
      2045:
        BN: 0.606
        ID: 1.119
        KH: 1.552
        LA: 0.586
        MM: 0.751
        MY: 0.942
        PH: 1.005
        SG: 0.696
        TH: 0.83
        VN: 1.508
      2050:
        BN: 0.516
        ID: 1.094
        KH: 1.509
        LA: 0.579
        MM: 0.768
        MY: 0.913
        PH: 0.972
        SG: 0.639
        TH: 0.825
        VN: 1.507
#should be in MWh, if not used = 0
    industry:
      2030: 0 #AEO8 BAS
      2035: 0
      2040: 0
      2045: 0
      2050: 0
    transport: #AEO8 BAS
      2030: 2344608000
      2035: 2795852000 
      2040: 3266424000
      2045: 3793143000
      2050: 4357987000
    services: #AEO8 BAS
      2030: 458222000
      2035: 544284000
      2040: 641976000
      2045: 756050000
      2050: 882617000
    agriculture: #All scenarios
      2030: 148864000
      2035: 184917000
      2040: 225522000
      2045: 273305000
      2050: 323614000
    residential: #AEO8 BAS
      2030: 744320000
      2035: 751298000
      2040: 765751000
      2045: 780473000
      2050: 792586000
  substitute_country_load:
    LA: MM



electricity:
  co2limit: 1e+9 #1e+9 20% #AEO6
  use_relative_targets: true
  co2_relative_targets:
    2030: 2.5 #1.8504  # 2,215.2 Mt CO2-eq in 2022
    2035: 2
    2040: 1.5
    2045: 1
    2050: 0.5
  powerplants_filter: "(DateOut >= 2030) or (DateOut != DateOut)" 
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc, OCGT, CCGT]
    StorageUnit: [battery, H2] 
    Store: [battery, H2]


lines:
  s_nom_max: 2

links:
  p_nom_max: 2

costs: 
  year: 2050
  discountrate: [0.05] 
  # for scenario
  #override:
    #marginal_cost:
      #solar: 10
      #onwind: 1
      #offwind: 1
  
fossil_reserves:
  oil: 19212.76 #TWh 11.8 billion bbo
  coal: 65651.8 #9,408.4 million tons (Mt), 6000 kcal/kg = 6.978 megawatt-hours (MWh)/ton

export:
  h2export: [0] #no export outside of the ASEAN region
  
sector:
  hydrogen:
    network: false
    network_routes: greenfield 
    gas_network_repurposing: false 
    underground_storage: true  
  #AMS target scenario
  land_transport_fuel_cell_share:
    ASEAN_2030: 0.04 
    ASEAN_2035: 0.08
    ASEAN_2040: 0.12
    ASEAN_2045: 0.16
    ASEAN_2050: 0.20 # in transport share 
  land_transport_electric_share:
    ASEAN_2030: 0.12 
    ASEAN_2035: 0.24
    ASEAN_2040: 0.36
    ASEAN_2045: 0.48
    ASEAN_2050: 0.60
  shipping_hydrogen_share:
    ASEAN_2030: 0.04 
    ASEAN_2035: 0.08
    ASEAN_2040: 0.12
    ASEAN_2045: 0.16
    ASEAN_2050: 0.20 # in transport share 
  co2_network: false 
  biomass_transport: false
  solid_biomass_potential: 1089 # TWh/a, biomass residues 
  biogas_potential: 43.56 # TWh/a, only from lifestock manure (4% of total residue)
  bio_pathway:
    2030: 0.30 
    2035: 0.60
    2040: 0.80
    2045: 0.95
    2050: 1.00     
  co2_sequestration_potential: 120 #MtCO2/a sequestration potential in 2050 
  co2_sequestration_cost: 37.66 #EUR/tCO2 for sequestration of CO2, ASEAN max=450$/Ton
  shipping_hydrogen_liquefaction: false
  space_heat_share: 0
  h2_cavern: false
  methanation: false
  helmeth: false
  dac: false
  SMR: false
  SMR CC: false
  lignite:
    spatial_lignite: true


focus_weights: # Focus weights based on land area
  BN: 0.001244
  KH: 0.041030
  ID: 0.404900
  LA: 0.055035
  MY: 0.070880
  MM: 0.165034
  PH: 0.065376
  SG: 0.000128
  TH: 0.118773
  VN: 0.077600

transmission_projects:
  enable: true
  include:
    EO8 - Final: true
  status:
  - in_planning
  - under_consideration
  - existing
  new_link_capacity: keep #keep or zero

